version: "2"
services:
  app:
    build: ./project
    links:
      - db
    ports:
      - "5000:5000"
    container_name: kios-engine
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    command: --max_allowed_packet=32505856
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro